import '../models/index.dart';
import '../models/Trip.dart';

// Mock Data Service
class MockDataService {
  static User? currentUser;

  static List<Driver> drivers = [
    Driver(id: '1', name: 'Nguyễn Văn A', phone: '0901234567'),
    Driver(id: '2', name: 'Trần Thị B', phone: '0912345678'),
    Driver(id: '3', name: 'Vũ Như Quân', phone: '0912345677'),
    Driver(id: '4', name: 'Vũ Văn Lương', phone: '0912345677'),
    Driver(id: '5', name: 'Nguyễn Văn Bình', phone: '0912345647'),
    Driver(id: '6', name: 'Tô Văn Hồng', phone: '0912345377'),
    Driver(id: '7', name: 'Đinh Văn Bình', phone: '0912315677'),
    Driver(id: '8', name: 'Bùi Văn Ca', phone: '0912445677'),
    Driver(id: '9', name: 'Vũ Văn Nam', phone: '0922345677'),

  ];

  static List<Vehicle> vehicles = [
    Vehicle(id: '1', type: '4 chỗ', licensePlate: '30A-12345', driverId: '1'),
    Vehicle(id: '2', type: '7 chỗ', licensePlate: '30B-67890', driverId: '2'),
    Vehicle(id: '3', type: '7 chỗ', licensePlate: '30B-67221', driverId: '3'),
    Vehicle(id: '4', type: '20 chỗ', licensePlate: '30B-67220', driverId: '4'),
    Vehicle(id: '5', type: '4 chỗ', licensePlate: '30B-67245', driverId: '5'),
    Vehicle(id: '6', type: '5 chỗ', licensePlate: '30B-68820', driverId: '6'),

  ];

  static List<Trip> trips = [
    // === BIDDING (8 trips) ===
    Trip(
      id: 'b1',
      fromLocation: 'Sân bay Nội Bài, Sóc Sơn, Hà Nội',
      toLocation: 'Bến xe Niệm Nghĩa, Lê Chân, Hải Phòng',
      requestedPrice: 500000,
      startTime: DateTime.now().add(Duration(hours: 2)),
      biddingEndTime: DateTime.now().add(Duration(minutes: 30)),
      participantCount: 5,
      vehicleType: '4 chỗ',
      notes: 'Có hàng cồng kềnh',
      status: TripStatus.bidding,
    ),
    Trip(
      id: 'b2',
      fromLocation: 'Nhà thờ Đức Bà, Quận 1, TP.HCM',
      toLocation: 'Chợ Đà Lạt, Lâm Đồng',
      requestedPrice: 1200000,
      startTime: DateTime.now().add(Duration(hours: 6)),
      biddingEndTime: DateTime.now().add(Duration(hours: 2)),
      participantCount: 4,
      vehicleType: '7 chỗ',
      status: TripStatus.bidding,
    ),
    Trip(
      id: 'b3',
      fromLocation: 'Cầu Rồng, Đà Nẵng',
      toLocation: 'Kinh thành Huế, Thừa Thiên Huế',
      requestedPrice: 700000,
      startTime: DateTime.now().add(Duration(hours: 3)),
      biddingEndTime: DateTime.now().add(Duration(minutes: 45)),
      participantCount: 2,
      vehicleType: '4 chỗ',
      status: TripStatus.bidding,
    ),
    Trip(
      id: 'b4',
      fromLocation: 'Bến Ninh Kiều, Cần Thơ',
      toLocation: 'Chợ Bông Sen, Sóc Trăng',
      requestedPrice: 350000,
      startTime: DateTime.now().add(Duration(hours: 1)),
      biddingEndTime: DateTime.now().add(Duration(minutes: 20)),
      participantCount: 1,
      vehicleType: '4 chỗ',
      status: TripStatus.bidding,
    ),
    Trip(
      id: 'b5',
      fromLocation: 'Tháp Trầm Hương, Nha Trang',
      toLocation: 'Chợ Đà Lạt, Lâm Đồng',
      requestedPrice: 750000,
      startTime: DateTime.now().add(Duration(hours: 4)),
      biddingEndTime: DateTime.now().add(Duration(hours: 1)),
      participantCount: 3,
      vehicleType: '7 chỗ',
      status: TripStatus.bidding,
    ),
    Trip(
      id: 'b6',
      fromLocation: 'Ga Thanh Hóa, TP Thanh Hóa',
      toLocation: 'Quảng trường Hồ Chí Minh, TP Vinh, Nghệ An',
      requestedPrice: 650000,
      startTime: DateTime.now().add(Duration(hours: 5)),
      biddingEndTime: DateTime.now().add(Duration(hours: 2)),
      participantCount: 6,
      vehicleType: '16 chỗ',
      notes: 'Đi tour du lịch',
      status: TripStatus.bidding,
    ),
    Trip(
      id: 'b7',
      fromLocation: 'Chùa Phật Tích, Bắc Ninh',
      toLocation: 'Hồ Hoàn Kiếm, Hà Nội',
      requestedPrice: 300000,
      startTime: DateTime.now().add(Duration(hours: 2)),
      biddingEndTime: DateTime.now().add(Duration(minutes: 15)),
      participantCount: 2,
      vehicleType: '4 chỗ',
      status: TripStatus.bidding,
    ),
    Trip(
      id: 'b8',
      fromLocation: 'Sân bay Phú Quốc, Kiên Giang',
      toLocation: 'Bến xe Rạch Giá, Kiên Giang',
      requestedPrice: 1100000,
      startTime: DateTime.now().add(Duration(hours: 8)),
      biddingEndTime: DateTime.now().add(Duration(hours: 3)),
      participantCount: 5,
      vehicleType: '16 chỗ',
      notes: 'Chở nhiều hành lý',
      status: TripStatus.bidding,
    ),

    // === PENDING (8 trips) ===
    Trip(
      id: 'p1',
      fromLocation: 'Bến xe Giáp Bát, Hà Nội',
      toLocation: 'Ga Nam Định, TP Nam Định',
      requestedPrice: 450000,
      startTime: DateTime.now().add(Duration(hours: 2)),
      biddingEndTime: DateTime.now().add(Duration(minutes: 30)),
      participantCount: 2,
      vehicleType: '4 chỗ',
      status: TripStatus.pending,
      bidPrice: 400000,
      selectedDriverId: 'd1',
      selectedVehicleId: 'v1',
    ),
    Trip(
      id: 'p2',
      fromLocation: 'Bến xe Miền Đông, TP.HCM',
      toLocation: 'Bãi Sau, Vũng Tàu',
      requestedPrice: 800000,
      startTime: DateTime.now().add(Duration(hours: 4)),
      biddingEndTime: DateTime.now().add(Duration(hours: 1)),
      participantCount: 3,
      vehicleType: '7 chỗ',
      status: TripStatus.pending,
      bidPrice: 750000,
      selectedDriverId: 'd2',
      selectedVehicleId: 'v2',
    ),
    Trip(
      id: 'p3',
      fromLocation: 'Ga Huế, Thừa Thiên Huế',
      toLocation: 'Chợ Đông Hà, Quảng Trị',
      requestedPrice: 600000,
      startTime: DateTime.now().add(Duration(hours: 3)),
      biddingEndTime: DateTime.now().add(Duration(minutes: 40)),
      participantCount: 1,
      vehicleType: '4 chỗ',
      status: TripStatus.pending,
      bidPrice: 550000,
      selectedDriverId: 'd3',
      selectedVehicleId: 'v3',
    ),
    Trip(
      id: 'p4',
      fromLocation: 'Cầu Rồng, Đà Nẵng',
      toLocation: 'Chợ Tam Kỳ, Quảng Nam',
      requestedPrice: 250000,
      startTime: DateTime.now().add(Duration(hours: 1)),
      biddingEndTime: DateTime.now().add(Duration(minutes: 20)),
      participantCount: 1,
      vehicleType: '4 chỗ',
      status: TripStatus.pending,
      bidPrice: 220000,
      selectedDriverId: 'd4',
      selectedVehicleId: 'v4',
    ),
    Trip(
      id: 'p5',
      fromLocation: 'Ga Hải Dương, Hải Dương',
      toLocation: 'Bến xe Mỹ Đình, Hà Nội',
      requestedPrice: 500000,
      startTime: DateTime.now().add(Duration(hours: 2)),
      biddingEndTime: DateTime.now().add(Duration(minutes: 30)),
      participantCount: 2,
      vehicleType: '7 chỗ',
      status: TripStatus.pending,
      bidPrice: 480000,
      selectedDriverId: 'd5',
      selectedVehicleId: 'v5',
    ),
    Trip(
      id: 'p6',
      fromLocation: 'Hồ Gươm, Hà Nội',
      toLocation: 'Tràng An, Ninh Bình',
      requestedPrice: 600000,
      startTime: DateTime.now().add(Duration(hours: 3)),
      biddingEndTime: DateTime.now().add(Duration(hours: 1)),
      participantCount: 4,
      vehicleType: '16 chỗ',
      status: TripStatus.pending,
      bidPrice: 570000,
      selectedDriverId: 'd6',
      selectedVehicleId: 'v6',
    ),
    Trip(
      id: 'p7',
      fromLocation: 'Chợ Bến Thành, Quận 1, TP.HCM',
      toLocation: 'Ga Biên Hòa, Đồng Nai',
      requestedPrice: 300000,
      startTime: DateTime.now().add(Duration(hours: 1)),
      biddingEndTime: DateTime.now().add(Duration(minutes: 15)),
      participantCount: 1,
      vehicleType: '4 chỗ',
      status: TripStatus.pending,
      bidPrice: 280000,
      selectedDriverId: 'd7',
      selectedVehicleId: 'v7',
    ),
    Trip(
      id: 'p8',
      fromLocation: 'Cầu Rồng, Đà Nẵng',
      toLocation: 'Phố cổ Hội An, Quảng Nam',
      requestedPrice: 200000,
      startTime: DateTime.now().add(Duration(hours: 1)),
      biddingEndTime: DateTime.now().add(Duration(minutes: 15)),
      participantCount: 2,
      vehicleType: '4 chỗ',
      status: TripStatus.pending,
      bidPrice: 180000,
      selectedDriverId: 'd8',
      selectedVehicleId: 'v8',
    ),

// === ACCEPTED (8 trips) ===
    Trip(
      id: 'a1',
      fromLocation: 'Bến xe Giáp Bát, Hà Nội',
      toLocation: 'Ga Bắc Giang, Bắc Giang',
      requestedPrice: 400000,
      startTime: DateTime.now().subtract(Duration(hours: 1)),
      biddingEndTime: DateTime.now().subtract(Duration(hours: 2)),
      participantCount: 2,
      status: TripStatus.accepted,
      bidPrice: 370000,
      selectedDriverId: 'd9',
      selectedVehicleId: 'v9',
    ),
    Trip(
      id: 'a2',
      fromLocation: 'Chợ Bến Thành, Quận 1, TP.HCM',
      toLocation: 'Địa đạo Củ Chi, TP.HCM',
      requestedPrice: 300000,
      startTime: DateTime.now().subtract(Duration(hours: 2)),
      biddingEndTime: DateTime.now().subtract(Duration(hours: 3)),
      participantCount: 1,
      status: TripStatus.accepted,
      bidPrice: 280000,
      selectedDriverId: 'd10',
      selectedVehicleId: 'v10',
    ),
    Trip(
      id: 'a3',
      fromLocation: 'Kinh thành Huế, Thừa Thiên Huế',
      toLocation: 'Cầu Rồng, Đà Nẵng',
      requestedPrice: 600000,
      startTime: DateTime.now().subtract(Duration(hours: 4)),
      biddingEndTime: DateTime.now().subtract(Duration(hours: 5)),
      participantCount: 3,
      status: TripStatus.accepted,
      bidPrice: 550000,
      selectedDriverId: 'd11',
      selectedVehicleId: 'v11',
    ),
    Trip(
      id: 'a4',
      fromLocation: 'Bến Ninh Kiều, Cần Thơ',
      toLocation: 'Chợ Châu Đốc, An Giang',
      requestedPrice: 500000,
      startTime: DateTime.now().subtract(Duration(hours: 1)),
      biddingEndTime: DateTime.now().subtract(Duration(hours: 2)),
      participantCount: 2,
      status: TripStatus.accepted,
      bidPrice: 480000,
      selectedDriverId: 'd12',
      selectedVehicleId: 'v12',
    ),
    Trip(
      id: 'a5',
      fromLocation: 'Tháp Trầm Hương, Nha Trang',
      toLocation: 'Chợ Phan Rang, Ninh Thuận',
      requestedPrice: 400000,
      startTime: DateTime.now().subtract(Duration(hours: 2)),
      biddingEndTime: DateTime.now().subtract(Duration(hours: 3)),
      participantCount: 2,
      status: TripStatus.accepted,
      bidPrice: 370000,
      selectedDriverId: 'd13',
      selectedVehicleId: 'v13',
    ),
    Trip(
      id: 'a6',
      fromLocation: 'Chợ Đà Lạt, Lâm Đồng',
      toLocation: 'Buôn Ma Thuột, Đắk Lắk',
      requestedPrice: 700000,
      startTime: DateTime.now().subtract(Duration(hours: 6)),
      biddingEndTime: DateTime.now().subtract(Duration(hours: 7)),
      participantCount: 3,
      status: TripStatus.accepted,
      bidPrice: 650000,
      selectedDriverId: 'd14',
      selectedVehicleId: 'v14',
    ),
    Trip(
      id: 'a7',
      fromLocation: 'Sân bay Phú Quốc, Kiên Giang',
      toLocation: 'Bến xe Hà Tiên, Kiên Giang',
      requestedPrice: 800000,
      startTime: DateTime.now().subtract(Duration(hours: 3)),
      biddingEndTime: DateTime.now().subtract(Duration(hours: 4)),
      participantCount: 4,
      status: TripStatus.accepted,
      bidPrice: 760000,
      selectedDriverId: 'd15',
      selectedVehicleId: 'v15',
    ),
    Trip(
      id: 'a8',
      fromLocation: 'Hồ Gươm, Hà Nội',
      toLocation: 'Thủy điện Hòa Bình, Hòa Bình',
      requestedPrice: 500000,
      startTime: DateTime.now().subtract(Duration(hours: 2)),
      biddingEndTime: DateTime.now().subtract(Duration(hours: 3)),
      participantCount: 2,
      status: TripStatus.accepted,
      bidPrice: 480000,
      selectedDriverId: 'd16',
      selectedVehicleId: 'v16',
    ),

// === RUNNING (8 trips) ===
    Trip(
      id: 'r1',
      fromLocation: 'Bến xe Mỹ Đình, Hà Nội',
      toLocation: 'Cửa khẩu Hữu Nghị, Lạng Sơn',
      requestedPrice: 900000,
      startTime: DateTime.now().subtract(Duration(minutes: 30)),
      biddingEndTime: DateTime.now().subtract(Duration(hours: 3)),
      participantCount: 3,
      status: TripStatus.running,
      bidPrice: 850000,
      selectedDriverId: 'd17',
      selectedVehicleId: 'v17',
    ),
    Trip(
      id: 'r2',
      fromLocation: 'Cầu Rồng, Đà Nẵng',
      toLocation: 'Ga Quảng Ngãi, Quảng Ngãi',
      requestedPrice: 700000,
      startTime: DateTime.now().subtract(Duration(minutes: 45)),
      biddingEndTime: DateTime.now().subtract(Duration(hours: 2)),
      participantCount: 2,
      status: TripStatus.running,
      bidPrice: 660000,
      selectedDriverId: 'd18',
      selectedVehicleId: 'v18',
    ),
    Trip(
      id: 'r3',
      fromLocation: 'Ga Huế, Thừa Thiên Huế',
      toLocation: 'Ga Đồng Hới, Quảng Bình',
      requestedPrice: 800000,
      startTime: DateTime.now().subtract(Duration(minutes: 20)),
      biddingEndTime: DateTime.now().subtract(Duration(hours: 2)),
      participantCount: 3,
      status: TripStatus.running,
      bidPrice: 770000,
      selectedDriverId: 'd19',
      selectedVehicleId: 'v19',
    ),
    Trip(
      id: 'r4',
      fromLocation: 'Chợ Bến Thành, Quận 1, TP.HCM',
      toLocation: 'Tòa thánh Cao Đài, Tây Ninh',
      requestedPrice: 600000,
      startTime: DateTime.now().subtract(Duration(minutes: 10)),
      biddingEndTime: DateTime.now().subtract(Duration(hours: 1)),
      participantCount: 1,
      status: TripStatus.running,
      bidPrice: 580000,
      selectedDriverId: 'd20',
      selectedVehicleId: 'v20',
    ),
    Trip(
      id: 'r5',
      fromLocation: 'Bến Ninh Kiều, Cần Thơ',
      toLocation: 'Chợ Vị Thanh, Hậu Giang',
      requestedPrice: 300000,
      startTime: DateTime.now().subtract(Duration(minutes: 15)),
      biddingEndTime: DateTime.now().subtract(Duration(hours: 1)),
      participantCount: 1,
      status: TripStatus.running,
      bidPrice: 280000,
      selectedDriverId: 'd21',
      selectedVehicleId: 'v21',
    ),
    Trip(
      id: 'r6',
      fromLocation: 'Tháp Trầm Hương, Nha Trang',
      toLocation: 'Sân bay Cam Ranh, Khánh Hòa',
      requestedPrice: 400000,
      startTime: DateTime.now().subtract(Duration(minutes: 40)),
      biddingEndTime: DateTime.now().subtract(Duration(hours: 2)),
      participantCount: 2,
      status: TripStatus.running,
      bidPrice: 370000,
      selectedDriverId: 'd22',
      selectedVehicleId: 'v22',
    ),
    Trip(
      id: 'r7',
      fromLocation: 'Chợ Đà Lạt, Lâm Đồng',
      toLocation: 'TP Bảo Lộc, Lâm Đồng',
      requestedPrice: 500000,
      startTime: DateTime.now().subtract(Duration(minutes: 50)),
      biddingEndTime: DateTime.now().subtract(Duration(hours: 2)),
      participantCount: 2,
      status: TripStatus.running,
      bidPrice: 470000,
      selectedDriverId: 'd23',
      selectedVehicleId: 'v23',
    ),
    Trip(
      id: 'r8',
      fromLocation: 'Hồ Gươm, Hà Nội',
      toLocation: 'Đại học Thái Nguyên, Thái Nguyên',
      requestedPrice: 450000,
      startTime: DateTime.now().subtract(Duration(minutes: 25)),
      biddingEndTime: DateTime.now().subtract(Duration(hours: 1)),
      participantCount: 2,
      status: TripStatus.running,
      bidPrice: 420000,
      selectedDriverId: 'd24',
      selectedVehicleId: 'v24',
    ),

// === COMPLETED (8 trips) ===
    Trip(
      id: 'c1',
      fromLocation: 'Bến xe Giáp Bát, Hà Nội',
      toLocation: 'Ga Hải Dương, Hải Dương',
      requestedPrice: 400000,
      startTime: DateTime.now().subtract(Duration(days: 1)),
      biddingEndTime: DateTime.now().subtract(Duration(days: 1, hours: 2)),
      participantCount: 2,
      status: TripStatus.completed,
      bidPrice: 380000,
      selectedDriverId: 'd25',
      selectedVehicleId: 'v25',
    ),
    Trip(
      id: 'c2',
      fromLocation: 'Chợ Bến Thành, Quận 1, TP.HCM',
      toLocation: 'Long An Stadium, Long An',
      requestedPrice: 500000,
      startTime: DateTime.now().subtract(Duration(days: 2)),
      biddingEndTime: DateTime.now().subtract(Duration(days: 2, hours: 3)),
      participantCount: 3,
      status: TripStatus.completed,
      bidPrice: 470000,
      selectedDriverId: 'd26',
      selectedVehicleId: 'v26',
    ),
    Trip(
      id: 'c3',
      fromLocation: 'Cầu Rồng, Đà Nẵng',
      toLocation: 'Chợ Tam Kỳ, Quảng Nam',
      requestedPrice: 300000,
      startTime: DateTime.now().subtract(Duration(days: 1)),
      biddingEndTime: DateTime.now().subtract(Duration(days: 1, hours: 1)),
      participantCount: 1,
      status: TripStatus.completed,
      bidPrice: 280000,
      selectedDriverId: 'd27',
      selectedVehicleId: 'v27',
    ),
    Trip(
      id: 'c4',
      fromLocation: 'Kinh thành Huế, Thừa Thiên Huế',
      toLocation: 'Động Phong Nha, Quảng Bình',
      requestedPrice: 700000,
      startTime: DateTime.now().subtract(Duration(days: 3)),
      biddingEndTime: DateTime.now().subtract(Duration(days: 3, hours: 2)),
      participantCount: 2,
      status: TripStatus.completed,
      bidPrice: 680000,
      selectedDriverId: 'd28',
      selectedVehicleId: 'v28',
    ),
    Trip(
      id: 'c5',
      fromLocation: 'Tháp Trầm Hương, Nha Trang',
      toLocation: 'Bãi biển Phan Thiết, Bình Thuận',
      requestedPrice: 1000000,
      startTime: DateTime.now().subtract(Duration(days: 5)),
      biddingEndTime: DateTime.now().subtract(Duration(days: 5, hours: 3)),
      participantCount: 4,
      status: TripStatus.completed,
      bidPrice: 950000,
      selectedDriverId: 'd29',
      selectedVehicleId: 'v29',
    ),
    Trip(
      id: 'c6',
      fromLocation: 'Bến Ninh Kiều, Cần Thơ',
      toLocation: 'Ga Vĩnh Long, Vĩnh Long',
      requestedPrice: 400000,
      startTime: DateTime.now().subtract(Duration(days: 2)),
      biddingEndTime: DateTime.now().subtract(Duration(days: 2, hours: 1)),
      participantCount: 2,
      status: TripStatus.completed,
      bidPrice: 370000,
      selectedDriverId: 'd30',
      selectedVehicleId: 'v30',
    ),
    Trip(
      id: 'c7',
      fromLocation: 'Chợ Đà Lạt, Lâm Đồng',
      toLocation: 'Tháp Trầm Hương, Nha Trang',
      requestedPrice: 800000,
      startTime: DateTime.now().subtract(Duration(days: 4)),
      biddingEndTime: DateTime.now().subtract(Duration(days: 4, hours: 2)),
      participantCount: 3,
      status: TripStatus.completed,
      bidPrice: 770000,
      selectedDriverId: 'd31',
      selectedVehicleId: 'v31',
    ),
    Trip(
      id: 'c8',
      fromLocation: 'Bến xe Gia Lâm, Hà Nội',
      toLocation: 'Ga Hải Phòng, Hải Phòng',
      requestedPrice: 500000,
      startTime: DateTime.now().subtract(Duration(days: 1)),
      biddingEndTime: DateTime.now().subtract(Duration(days: 1, hours: 2)),
      participantCount: 2,
      status: TripStatus.completed,
      bidPrice: 480000,
      selectedDriverId: 'd32',
      selectedVehicleId: 'v32',
    ),

// === CANCELED (8 trips) ===
    Trip(
      id: 'x1',
      fromLocation: 'Hồ Gươm, Hà Nội',
      toLocation: 'Thủy điện Hòa Bình, Hòa Bình',
      requestedPrice: 400000,
      startTime: DateTime.now().subtract(Duration(days: 1)),
      biddingEndTime: DateTime.now().subtract(Duration(days: 1, hours: 2)),
      participantCount: 1,
      status: TripStatus.canceled,
      bidPrice: 370000,
      selectedDriverId: 'd33',
      selectedVehicleId: 'v33',
    ),
    Trip(
      id: 'x2',
      fromLocation: 'Chợ Bến Thành, Quận 1, TP.HCM',
      toLocation: 'Tòa thánh Cao Đài, Tây Ninh',
      requestedPrice: 500000,
      startTime: DateTime.now().subtract(Duration(days: 2)),
      biddingEndTime: DateTime.now().subtract(Duration(days: 2, hours: 2)),
      participantCount: 2,
      status: TripStatus.canceled,
      bidPrice: 480000,
      selectedDriverId: 'd34',
      selectedVehicleId: 'v34',
    ),
    Trip(
      id: 'x3',
      fromLocation: 'Cầu Rồng, Đà Nẵng',
      toLocation: 'Ga Quảng Ngãi, Quảng Ngãi',
      requestedPrice: 600000,
      startTime: DateTime.now().subtract(Duration(days: 1)),
      biddingEndTime: DateTime.now().subtract(Duration(days: 1, hours: 2)),
      participantCount: 2,
      status: TripStatus.canceled,
      bidPrice: 570000,
      selectedDriverId: 'd35',
      selectedVehicleId: 'v35',
    ),
    Trip(
      id: 'x4',
      fromLocation: 'Kinh thành Huế, Thừa Thiên Huế',
      toLocation: 'Cầu Rồng, Đà Nẵng',
      requestedPrice: 400000,
      startTime: DateTime.now().subtract(Duration(days: 3)),
      biddingEndTime: DateTime.now().subtract(Duration(days: 3, hours: 1)),
      participantCount: 1,
      status: TripStatus.canceled,
      bidPrice: 380000,
      selectedDriverId: 'd36',
      selectedVehicleId: 'v36',
    ),
    Trip(
      id: 'x5',
      fromLocation: 'Bến Ninh Kiều, Cần Thơ',
      toLocation: 'Chợ Sóc Trăng, Sóc Trăng',
      requestedPrice: 300000,
      startTime: DateTime.now().subtract(Duration(days: 2)),
      biddingEndTime: DateTime.now().subtract(Duration(days: 2, hours: 1)),
      participantCount: 1,
      status: TripStatus.canceled,
      bidPrice: 280000,
      selectedDriverId: 'd37',
      selectedVehicleId: 'v37',
    ),
    Trip(
      id: 'x6',
      fromLocation: 'Tháp Trầm Hương, Nha Trang',
      toLocation: 'Chợ Đà Lạt, Lâm Đồng',
      requestedPrice: 700000,
      startTime: DateTime.now().subtract(Duration(days: 4)),
      biddingEndTime: DateTime.now().subtract(Duration(days: 4, hours: 2)),
      participantCount: 3,
      status: TripStatus.canceled,
      bidPrice: 670000,
      selectedDriverId: 'd38',
      selectedVehicleId: 'v38',
    ),
    Trip(
      id: 'x7',
      fromLocation: 'Bến xe Gia Lâm, Hà Nội',
      toLocation: 'Ga Hải Phòng, Hải Phòng',
      requestedPrice: 500000,
      startTime: DateTime.now().subtract(Duration(days: 1)),
      biddingEndTime: DateTime.now().subtract(Duration(days: 1, hours: 2)),
      participantCount: 2,
      status: TripStatus.canceled,
      bidPrice: 470000,
      selectedDriverId: 'd39',
      selectedVehicleId: 'v39',
    ),
    Trip(
      id: 'x8',
      fromLocation: 'Sân bay Phú Quốc, Kiên Giang',
      toLocation: 'Bến xe Rạch Giá, Kiên Giang',
      requestedPrice: 1000000,
      startTime: DateTime.now().subtract(Duration(days: 5)),
      biddingEndTime: DateTime.now().subtract(Duration(days: 5, hours: 2)),
      participantCount: 4,
      status: TripStatus.canceled,
      bidPrice: 950000,
      selectedDriverId: 'd40',
      selectedVehicleId: 'v40',
    ),

  ];

  static Future<User?> login(String phone, String password) async {
    await Future.delayed(Duration(seconds: 1)); // Simulate network delay

    if (phone == '0123456789' && password == '123456') {
      currentUser = User(
        id: '1',
        name: 'Đại lý test',
        phone: phone,
        role: 2,
        points: 100,
        token: 'mock_token_123',
      );
      return currentUser;
    }
    if (phone == '9876543210' && password == '123456') {
      currentUser = User(
        id: '2',
        name: 'Tài xế A',
        role: 3,
        phone: phone,
        points: 100,
        token: 'mock_token_1234',
      );
      return currentUser;
    }
    return null;
  }

  static Future<void> placeBid(String tripId, double bidPrice, String driverId, String vehicleId) async {
    await Future.delayed(Duration(seconds: 1));

    int index = trips.indexWhere((trip) => trip.id == tripId);
    if (index != -1) {
      trips[index] = trips[index].copyWith(
        status: TripStatus.pending,
        bidPrice: bidPrice,
        selectedDriverId: driverId,
        selectedVehicleId: vehicleId,
      );
    }
  }

  static Future<void> cancelTrip(String tripId) async {
    await Future.delayed(Duration(seconds: 1));

    if (currentUser != null) {
      currentUser = User(
        id: currentUser!.id,
        name: currentUser!.name,
        phone: currentUser!.phone,
        points: currentUser!.points - 10,
        token: currentUser!.token,
        role: currentUser!.role,
      );
    }

    int index = trips.indexWhere((trip) => trip.id == tripId);
    if (index != -1) {
      trips[index] = trips[index].copyWith(status: TripStatus.bidding);
    }
  }

  static Future<void> addExtraCost(String tripId, String cost) async {
    await Future.delayed(Duration(milliseconds: 500));

    int index = trips.indexWhere((trip) => trip.id == tripId);
    if (index != -1) {
      List<String> newCosts = List.from(trips[index].extraCosts);
      newCosts.add(cost);
      trips[index] = trips[index].copyWith(extraCosts: newCosts);
    }
  }
}
