// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjg4VTC2rWmE9m6AAXXY5LTyIlS2XYq5E',
    appId: '1:437619387798:web:c99d239a738ea4e38841b7',
    messagingSenderId: '437619387798',
    projectId: 'easy-rides-bd138',
    authDomain: 'easy-rides-bd138.firebaseapp.com',
    databaseURL: 'https://easy-rides-bd138-default-rtdb.firebaseio.com',
    storageBucket: 'easy-rides-bd138.firebasestorage.app',
    measurementId: 'G-Y2L9TMM9HV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdP4_OHhzNC8T1LrKgqpjZNowMfXDObbQ',
    appId: '1:437619387798:android:90aff15a4d97c35d8841b7',
    messagingSenderId: '437619387798',
    projectId: 'easy-rides-bd138',
    databaseURL: 'https://easy-rides-bd138-default-rtdb.firebaseio.com',
    storageBucket: 'easy-rides-bd138.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCei69DMPnrzJ-LeOk1kmxmgE2n8wuk864',
    appId: '1:437619387798:ios:86c82a0f562f62188841b7',
    messagingSenderId: '437619387798',
    projectId: 'easy-rides-bd138',
    databaseURL: 'https://easy-rides-bd138-default-rtdb.firebaseio.com',
    storageBucket: 'easy-rides-bd138.firebasestorage.app',
    iosBundleId: 'com.ios.bubdle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCei69DMPnrzJ-LeOk1kmxmgE2n8wuk864',
    appId: '1:437619387798:ios:a339b8b032db743c8841b7',
    messagingSenderId: '437619387798',
    projectId: 'easy-rides-bd138',
    databaseURL: 'https://easy-rides-bd138-default-rtdb.firebaseio.com',
    storageBucket: 'easy-rides-bd138.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjg4VTC2rWmE9m6AAXXY5LTyIlS2XYq5E',
    appId: '1:437619387798:web:7a7d87fc7018ed388841b7',
    messagingSenderId: '437619387798',
    projectId: 'easy-rides-bd138',
    authDomain: 'easy-rides-bd138.firebaseapp.com',
    databaseURL: 'https://easy-rides-bd138-default-rtdb.firebaseio.com',
    storageBucket: 'easy-rides-bd138.firebasestorage.app',
    measurementId: 'G-M6NKZK5RY6',
  );
}
